name: Deploy image to GHCR

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v3

    - name: "Login to GitHub Container Registry"
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: "Get lowercased repository owner name"
      run: |
        echo "OWNER_LC=${OWNER,,}" >> ${GITHUB_ENV}
      env:
        OWNER: "${{ github.repository_owner }}"

    - name: "Build image"
      run: |
        docker build . --tag ghcr.io/${{ OWNER_LC }}/pushserver:latest
        docker push ghcr.io/${{ OWNER_LC }}/pushserver:latest
